version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"
    networks:
      - sender
      - recipient

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # RabbitMQ Management UI
    networks:
      - sender
      - recipient

  micro-sender:
    build: ./micro-sender
    container_name: micro-sender
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - sender

  micro-recipient:
    build: ./micro-recipient
    container_name: micro-recipient
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - recipient

  micro-collector:
    build: ./micro-collector
    container_name: micro-collector
    ports:
      - "8083:8080"
    depends_on:
      - micro-recipient
      - postgres
    networks:
      - recipient

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - sender
      - recipient

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - sender
      - recipient

networks:
  sender:
  recipient:
