apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-recipient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-recipient
  template:
    metadata:
      labels:
        app: micro-recipient
    spec:
      containers:
        - name: micro-recipient
          image: rajatpal96/micro-recipient:latest  # Your built image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: micro-recipient
spec:
  selector:
    app: micro-recipient
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: NodePort