apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-sender
  template:
    metadata:
      labels:
        app: micro-sender
    spec:
      containers:
        - name: micro-sender
          image: rajatpal96/micro-sender:latest  # Your built image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: micro-sender
spec:
  selector:
    app: micro-sender
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: NodePort  # For local access: access via minikube IP:nodePort