apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-collector
  template:
    metadata:
      labels:
        app: micro-collector
    spec:
      containers:
        - name: micro-collector
          image: rajatpal96/micro-collector:latest  # Your built image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: micro-collector
spec:
  selector:
    app: micro-collector
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: NodePort