apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'micro-sender'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['micro-sender.default.svc.cluster.local:8081']
      - job_name: 'micro-recipient'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['micro-recipient.default.svc.cluster.local:8082']
      - job_name: 'micro-collector'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['micro-collector.default.svc.cluster.local:8083']